export const NAVIGATION = {
  HOME_SCREEN: "HOME_SCREEN",
  PRODUCT_DETAILS: "PRODUCT_DETAILS",
  ALL_PRODUCTS: "ALL_PRODUCTS",
  CUSTOMIZATION_SCREEN: "CUSTOMIZATION_SCREEN",
  SPLASH_SCREEN: "SPLASH_SCREEN",
  AUTH_SCREEN: "AUTH_SCREEN",
  OTP_SCREEN: "OTP_SCREEN",
  MEASUREMENTS: "MEASUREMENTS",
};
